language: node_js
node_js:
  - "6"
  - "7"
script: echo "npm test temporarily disabled"
deploy:
  provider: npm
  email: huttarichard@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
